name: Build boot.img (mainline 5.10.209 + rubens)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev libncurses-dev gcc-aarch64-linux-gnu
      - name: Fix mkbootimg tool (safe)
        run: |
          sudo apt update
          sudo apt install -y android-sdk-libsparse-utils
          if [ -f /usr/lib/android-sdk/mkbootimg ]; then
            sudo ln -sf /usr/lib/android-sdk/mkbootimg /usr/local/bin/mkbootimg
            sudo chmod +x /usr/local/bin/mkbootimg
          elif [ -f /usr/bin/mkbootimg ]; then
            sudo ln -sf /usr/bin/mkbootimg /usr/local/bin/mkbootimg
          fi


      - name: Fix mkbootimg tool
        run: |
          sudo apt remove mkbootimg -y || true

      - name: Build boot.img
        run: |
          ./build_bootimg.sh

      - name: Upload boot.img
        uses: actions/upload-artifact@v4
        with:
          name: boot-img
          path: boot.img
